/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.agura.parserpuml.vista;

import com.agura.parserpuml.controlador.Controlador;
import java.awt.Component;
import java.io.File;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author agustin
 */
@SuppressWarnings("serial")
public class Principal extends javax.swing.JFrame implements InterfazVista {

    /**
     * Creates new form ParserJFrame
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selCarpetaJpanel = new javax.swing.JPanel();
        btnExplorar = new javax.swing.JButton();
        txtCarpetaSeleccionada = new javax.swing.JTextField();
        archivosSelJpanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaArchivosSel = new javax.swing.JList<>();
        btnSalir = new javax.swing.JButton();
        btnQuitarPath = new javax.swing.JButton();
        btnGenerarJava = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        selCarpetaJpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccionar carpeta"));

        btnExplorar.setText("Explorar...");
        btnExplorar.setActionCommand("AbrirCarpetaAccion");

        txtCarpetaSeleccionada.setEditable(false);

        javax.swing.GroupLayout selCarpetaJpanelLayout = new javax.swing.GroupLayout(selCarpetaJpanel);
        selCarpetaJpanel.setLayout(selCarpetaJpanelLayout);
        selCarpetaJpanelLayout.setHorizontalGroup(
            selCarpetaJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selCarpetaJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCarpetaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnExplorar)
                .addContainerGap())
        );
        selCarpetaJpanelLayout.setVerticalGroup(
            selCarpetaJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, selCarpetaJpanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(selCarpetaJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnExplorar)
                    .addComponent(txtCarpetaSeleccionada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        archivosSelJpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Archivos seleccionados"));

        listaArchivosSel.setModel(modeloListaPathSel);
        jScrollPane1.setViewportView(listaArchivosSel);

        javax.swing.GroupLayout archivosSelJpanelLayout = new javax.swing.GroupLayout(archivosSelJpanel);
        archivosSelJpanel.setLayout(archivosSelJpanelLayout);
        archivosSelJpanelLayout.setHorizontalGroup(
            archivosSelJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivosSelJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        archivosSelJpanelLayout.setVerticalGroup(
            archivosSelJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(archivosSelJpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnSalir.setText("Salir");
        btnSalir.setActionCommand("SalirAccion");

        btnQuitarPath.setText("Quitar");
        btnQuitarPath.setActionCommand("QuitarPathAccion");
        btnQuitarPath.setEnabled(false);

        btnGenerarJava.setText("Generar");
        btnGenerarJava.setActionCommand("ParserAccion");
        btnGenerarJava.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(selCarpetaJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnQuitarPath, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarJava, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(144, 144, 144)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(archivosSelJpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selCarpetaJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(archivosSelJpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuitarPath)
                    .addComponent(btnGenerarJava))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void setControlador(Controlador c) {
        this.addWindowListener(c);
        for (Component component : this.getContentPane().getComponents()) {
            if (component instanceof JButton) {
                ((JButton) component).addActionListener(c);
            } else if (component instanceof JTextField) {
                ((JTextField) component).addKeyListener(c);
            }
        }
        for (Component component : this.selCarpetaJpanel.getComponents()) {
            if (component instanceof JButton) {
                ((JButton) component).addActionListener(c);
            } else if (component instanceof JTextField) {
                ((JTextField) component).addKeyListener(c);
            }
        }
        for (Component component : this.archivosSelJpanel.getComponents()) {
            if (component instanceof JButton) {
                ((JButton) component).addActionListener(c);
            } else if (component instanceof JTextField) {
                ((JTextField) component).addKeyListener(c);
            }
        }
    }

    @Override
    public void iniciaVista() {
        setTitle("PlantUML a Java");
        setLocationRelativeTo(null);
        setVisible(true);
    }

    @Override
    public void abrirDialogoSeleccionarCarpeta() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        chooser.setMultiSelectionEnabled(true);
        chooser.addChoosableFileFilter(new FileNameExtensionFilter("PlantUML Documents", "puml"));
        chooser.removeChoosableFileFilter(chooser.getChoosableFileFilters()[0]);
        int btnElegido = chooser.showOpenDialog(this);
        this.txtCarpetaSeleccionada.setText("");
        this.modeloListaPathSel.clear();
        if (btnElegido == JFileChooser.APPROVE_OPTION) {
            this.btnQuitarPath.setEnabled(false);
            this.txtCarpetaSeleccionada.setText(chooser.getSelectedFile().getParent());
            int cont = 0;
            for (File archivo : chooser.getSelectedFiles()) {
                this.modeloListaPathSel.addElement(archivo.getAbsolutePath());
                cont++;
            }
            if (cont > 0) {
                this.btnQuitarPath.setEnabled(true);
                this.btnGenerarJava.setEnabled(true);
            }
        }
    }

    @Override
    public void quitarPathCarpeta() {
        this.listaArchivosSel.getSelectedValuesList().forEach(path -> {
            this.modeloListaPathSel.removeElement(path);
        });
        this.btnQuitarPath.setEnabled(true);
        this.btnGenerarJava.setEnabled(true);
        if (this.modeloListaPathSel.isEmpty()) {
            this.btnQuitarPath.setEnabled(false);
            this.btnGenerarJava.setEnabled(false);
        }
    }

    @Override
    public void imprimeMensaje(String mensaje, Exception e) {
        if (mensaje != null) {
            JOptionPane.showMessageDialog(this, mensaje, "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrio una excepción: " + e.toString(), "Información", JOptionPane.ERROR_MESSAGE);
        }
    }

    @Override
    public void cierraSistema() {
//        int resp = JOptionPane.showConfirmDialog(this, "¿Seguro desea salir?", "Información", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

//        if (resp == JOptionPane.YES_OPTION) {
            this.dispose();
//        }
    }

    @Override
    public void update(String... params) {
        try {
            Method metodo;
            if (params.length == 1) {
                metodo = this.getClass().getDeclaredMethod(params[0]);
                metodo.invoke(this);
            } else if (params.length > 1) {
                metodo = this.getClass().getDeclaredMethod(params[0], String.class, Exception.class);
                if (params[1] != null) {
                    metodo.invoke(this, params[1], null);
                }
                if (params[2] != null) {
                    metodo.invoke(this, params[1], new Exception(params[2]));
                }
            }
            //imprimeMensaje(null);
        } catch (NumberFormatException | NoSuchMethodException | SecurityException e) {
            imprimeMensaje(null, e);
        } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            imprimeMensaje(null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel archivosSelJpanel;
    private javax.swing.JButton btnExplorar;
    private javax.swing.JButton btnGenerarJava;
    private javax.swing.JButton btnQuitarPath;
    private javax.swing.JButton btnSalir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaArchivosSel;
    private javax.swing.JPanel selCarpetaJpanel;
    private javax.swing.JTextField txtCarpetaSeleccionada;
    // End of variables declaration//GEN-END:variables
    public DefaultListModel<String> modeloListaPathSel = new DefaultListModel<>();

}
